// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCc39cP3c_32aA3U5qaObPd8a9EvSMJiY',
    appId: '1:129286132545:web:718c74369f87433a4407c0',
    messagingSenderId: '129286132545',
    projectId: 'attendify-90234',
    authDomain: 'attendify-90234.firebaseapp.com',
    storageBucket: 'attendify-90234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBcozxyLi7fOnGrzr8NjczFQWdY9ZPFnA',
    appId: '1:129286132545:android:8f498a0fc0b34d674407c0',
    messagingSenderId: '129286132545',
    projectId: 'attendify-90234',
    storageBucket: 'attendify-90234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRFySS79v88blykrw1kKhFs5uxscCfFU',
    appId: '1:129286132545:ios:efb80462343eda9d4407c0',
    messagingSenderId: '129286132545',
    projectId: 'attendify-90234',
    storageBucket: 'attendify-90234.appspot.com',
    iosBundleId: 'com.caca.attendify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgRFySS79v88blykrw1kKhFs5uxscCfFU',
    appId: '1:129286132545:ios:efb80462343eda9d4407c0',
    messagingSenderId: '129286132545',
    projectId: 'attendify-90234',
    storageBucket: 'attendify-90234.appspot.com',
    iosBundleId: 'com.caca.attendify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCc39cP3c_32aA3U5qaObPd8a9EvSMJiY',
    appId: '1:129286132545:web:18420090250e962c4407c0',
    messagingSenderId: '129286132545',
    projectId: 'attendify-90234',
    authDomain: 'attendify-90234.firebaseapp.com',
    storageBucket: 'attendify-90234.appspot.com',
  );
}
